#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Math_App.Droid.Resource", IsApplication=true)]

namespace Math_App.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int accent = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int accent_light = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int primary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int white = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int window_background = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bart = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int delete = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int hist_left = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int hist_right = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int maarten = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int text_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tom = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070032
			public const int Addition = 2131165234;
			
			// aapt resource value: 0x7f07002f
			public const int BracketLeft = 2131165231;
			
			// aapt resource value: 0x7f070031
			public const int BracketRight = 2131165233;
			
			// aapt resource value: 0x7f070021
			public const int Delete = 2131165217;
			
			// aapt resource value: 0x7f070026
			public const int Devide = 2131165222;
			
			// aapt resource value: 0x7f070024
			public const int Eight = 2131165220;
			
			// aapt resource value: 0x7f070028
			public const int Five = 2131165224;
			
			// aapt resource value: 0x7f070027
			public const int Four = 2131165223;
			
			// aapt resource value: 0x7f070033
			public const int FracionA = 2131165235;
			
			// aapt resource value: 0x7f070036
			public const int FracionAdd = 2131165238;
			
			// aapt resource value: 0x7f070034
			public const int FracionB = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int FracionC = 2131165237;
			
			// aapt resource value: 0x7f070018
			public const int GridAnswer = 2131165208;
			
			// aapt resource value: 0x7f070014
			public const int GridColor = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int GridContainer = 2131165203;
			
			// aapt resource value: 0x7f070017
			public const int GridEquation = 2131165207;
			
			// aapt resource value: 0x7f070015
			public const int GridImage = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int GridTitle = 2131165206;
			
			// aapt resource value: 0x7f070019
			public const int Image = 2131165209;
			
			// aapt resource value: 0x7f07002e
			public const int Minus = 2131165230;
			
			// aapt resource value: 0x7f07002a
			public const int Multiply = 2131165226;
			
			// aapt resource value: 0x7f070025
			public const int Nine = 2131165221;
			
			// aapt resource value: 0x7f07002b
			public const int One = 2131165227;
			
			// aapt resource value: 0x7f070022
			public const int Revert = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int Seven = 2131165219;
			
			// aapt resource value: 0x7f070020
			public const int ShowMe = 2131165216;
			
			// aapt resource value: 0x7f070029
			public const int Six = 2131165225;
			
			// aapt resource value: 0x7f07002d
			public const int Three = 2131165229;
			
			// aapt resource value: 0x7f07002c
			public const int Two = 2131165228;
			
			// aapt resource value: 0x7f070030
			public const int Zero = 2131165232;
			
			// aapt resource value: 0x7f070037
			public const int answer = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int calculation = 2131165240;
			
			// aapt resource value: 0x7f070002
			public const int explanation = 2131165186;
			
			// aapt resource value: 0x7f070012
			public const int gallery = 2131165202;
			
			// aapt resource value: 0x7f07003d
			public const int grid = 2131165245;
			
			// aapt resource value: 0x7f07001c
			public const int hlTopBar = 2131165212;
			
			// aapt resource value: 0x7f070011
			public const int imageButton1 = 2131165201;
			
			// aapt resource value: 0x7f07001d
			public const int imageButton2 = 2131165213;
			
			// aapt resource value: 0x7f07000b
			public const int imageView1 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int imageView2 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int imageView3 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int imageView4 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int imageView5 = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int imageview1 = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout1 = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int linearLayout2 = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout3 = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout4 = 2131165191;
			
			// aapt resource value: 0x7f070039
			public const int linearLayout5 = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int listView1 = 2131165242;
			
			// aapt resource value: 0x7f070001
			public const int nameAndLevel = 2131165185;
			
			// aapt resource value: 0x7f07003b
			public const int page3_answer = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int page3_equation = 2131165244;
			
			// aapt resource value: 0x7f070006
			public const int page4_answer = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int page4_equation = 2131165193;
			
			// aapt resource value: 0x7f07001e
			public const int tableId = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int tableRow1 = 2131165215;
			
			// aapt resource value: 0x7f070010
			public const int textLevel = 2131165200;
			
			// aapt resource value: 0x7f070005
			public const int textView1 = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int textView2 = 2131165192;
			
			// aapt resource value: 0x7f07001b
			public const int tvHome = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int tvName = 2131165210;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ButtonAnimation = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FifthPage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FourthPage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Gridview = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int layout2 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int layout3 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Listview = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SecondPage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ThirdPage = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int Dialog_Cancel = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int Dialog_Ok = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int RekenAppTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int RekenAppTheme_Base = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
